services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "8080:8080"
    networks:
      - chatbot-network

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
